version: '3.8'

services:
  app:
    image: aneury29/practica-4
    ports:
      - "${APP_PORT:-8080}:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - app_db
  app_db:
    container_name: db
    image: postgres:latest
    expose:
      - "${DB_PORT:-5432}"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - db-data:$DB_VOLUME_PATH
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT:-8082}:80"
    env_file:
      - .env
    environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER:-DB_USER@email.com}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-DB_PASSWORD}
    depends_on:
      - app_db

volumes:
  db-data:
