version: '3.8'
services:
  activemq:
    image: 'apache/activemq-classic:latest'
    ports:
      - '61616:61616'
      - '8161:8161'
  sensor-cliente1:
    image: 'jorgetuma/cliente-sensores:latest'
    depends_on:
      - activemq
  sensor-cliente2:
      image: 'jorgetuma/cliente-sensores:latest'
      depends_on:
        - activemq
  app-web:
    image: 'jorgetuma/app-web:latest'
    ports:
      - '8080:8080'
    depends_on:
      - activemq