version: '3.8'

services:
  app:
    image: aneury29/practica6
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    restart: always
    depends_on:
      - app_db
  app2:
    image: aneury29/practica6
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - PORT=8081
    restart: always
    depends_on:
      - app_db
  app_db:
    container_name: db
    image: postgres:latest
    expose:
      - "${DB_PORT:-5432}"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - db-data:$DB_VOLUME_PATH
volumes:
  db-data:
