package com.grupo5.practica7.encapsulaciones;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Reserva")
public class Reserva {
    @DynamoDBHashKey(attributeName = "idReserva")
    @DynamoDBAutoGeneratedKey
    private String idReserva;
    @DynamoDBAttribute(attributeName = "id")
    private  String id;
    @DynamoDBAttribute(attributeName = "nombre")
    private String nombre;
    @DynamoDBAttribute(attributeName = "correo")
    private String correo;
    @DynamoDBAttribute(attributeName = "laboratorio")
    private String laboratorio;
    @DynamoDBAttribute(attributeName = "fechaReserva")
    private String fechaReserva;

    public Reserva() {

    }

    public Reserva(String id, String nombre, String correo, String laboratorio, String fechaReserva) {
        this.id = id;
        this.nombre = nombre;
        this.correo = correo;
        this.laboratorio = laboratorio;
        this.fechaReserva = fechaReserva;
    }

    public String getIdReserva() {
        return idReserva;
    }

    public void setIdReserva(String idReserva) {
        this.idReserva = idReserva;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getLaboratorio() {
        return laboratorio;
    }

    public void setLaboratorio(String laboratorio) {
        this.laboratorio = laboratorio;
    }

    public String getFechaReserva() {
        return fechaReserva;
    }

    public void setFechaReserva(String fechaReserva) {
        this.fechaReserva = fechaReserva;
    }
}
